version: '3'
services:
  nginx:
    image: nginx:1.13
    ports:
    - "80:80"
    volumes:
    - ./html:/var/www/html/
    - ./etc/nginx:/etc/nginx/conf.d
    networks:
    - public-network
  php-fpm:
    image: registry.cn-hangzhou.aliyuncs.com/lluck42/php-fpm:7.2.8-fpm-stretch
    ports:
    - "9000:9000"
    volumes:
    - ./html:/var/www/html/
    networks:
    - public-network
  mysql:
    image: mysql:5.6
    ports: 
    - "3306:3306"
    volumes:
    - ./data:/var/lib/mysql
    - ./etc/mysql:/etc/mysql/conf.d/
    environment:
      MYSQL_ROOT_PASSWORD: a.123456
    networks:
    - public-network
  # mysql1:
  #   image: mysql:8.0
  #   command: --default-authentication-plugin=mysql_native_password
  #   ports: 
  #   - "3307:3306"
  #   volumes:
  #   - ./data1:/var/lib/mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: a.123456
  #   networks:
  #   - public-network
  # redis:
  #     image: redis:3.2
  #     ports:
  #     - "6379:6379"
  #     networks:
  #     - public-network
networks:
    public-network:
