web:
  image: nginx:latest
  ports:
  - "80:80"
  volumes:
  - ./code:/code
  - ./etc/nginx:/etc/nginx/conf.d
  links:
  - php
php:
  build: ./docker/php/
  volumes:
  - ./code:/code
  links:
  - mysql
mysql:
  image: mysql:latest
  ports: 
  - "3306:3306"
  volumes:
  - ./data:/var/lib/mysql
  - ./etc/mysql:/etc/mysql/conf.d/
  environment:
    MYSQL_ROOT_PASSWORD: a.123456